easy_admin:
  design:
    menu:
      - label: 'Gestion'
        icon: 'home'
       
        children:
          - {entity: 'City', icon: 'globe', label: 'Villes'}
          - {entity: 'Tag', icon: 'home', label: 'Tags'}
          - {entity: 'User', icon: 'calendar', label: 'Utilisateurs'}
          