easy_admin:
  entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - isActive
                    - firstname
                    - name
                    - username
                    - birthdate
                    - email 
                    - avatar
                    - points
                    - description
                    - createdAt
                    - roles


                    
                actions:
                    - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }