easy_admin:
  entities:
        City:
            class: App\Entity\City
            list:
                fields:
                    - id
                    - cityName
                    - countryName
                    - geonameId
                    
                actions:
                    - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary' }
                    - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }

            form: 
                fields:
                    - { property: 'tag', label: 'Tags de la ville' }
                    - { property: 'weather', label: 'Temperatures moyennes par mois' }

                   
                    
                    